In [1]:
import pandas as pd
edgelist=pd.read_csv('largestCompKEGGigraph.txt',sep=' ')
ovarian_expression1=pd.read_csv('Ovarian_expression_1.txt', sep='\t')
ovarian_expression2=pd.read_csv('Ovarian_expression_2.txt', sep='\t')
ovarian_expression3=pd.read_csv('Ovarian_expression_3.txt', sep='\t')
ovarian_expression4=pd.read_csv('Ovarian_expression_4.txt', sep='\t')
ovarian_expression5=pd.read_csv('Ovarian_expression_5.txt', sep='\t')
ovarian_expression6=pd.read_csv('Ovarian_expression_6.txt', sep='\t')
ovarian_expression7=pd.read_csv('Ovarian_expression_7.txt', sep='\t')
ovarian_expression8=pd.read_csv('Ovarian_expression_8.txt', sep='\t')
ovarian_expression9=pd.read_csv('Ovarian_expression_9.txt', sep='\t')
ovarian_expression10=pd.read_csv('Ovarian_expression_10.txt', sep='\t')

In [2]:
nodes=pd.read_csv('Sample3.txt')
Kegg_gene=list(nodes.iloc[:,0])

In [3]:
# Calculate the expression data from the 3 datasets
import scipy as sp
import scipy.stats
ova_genes=list(ovarian_expression1.index)

def calculate_spearman_corr(expression):
    rho, pval = sp.stats.spearmanr(expression,axis=1)
    return(rho)

In [4]:
#construct the matrix of spearman correlation of the genes from each experiment
# NOTE: authors used dataset 2,3 and 7 (GSE14764 GSE17260 GSE9891)
rho1=calculate_spearman_corr(ovarian_expression1)
rho2=calculate_spearman_corr(ovarian_expression2)
rho3=calculate_spearman_corr(ovarian_expression3)
rho4=calculate_spearman_corr(ovarian_expression4)
rho5=calculate_spearman_corr(ovarian_expression5)
rho6=calculate_spearman_corr(ovarian_expression6)
rho7=calculate_spearman_corr(ovarian_expression7)
rho8=calculate_spearman_corr(ovarian_expression8)
rho9=calculate_spearman_corr(ovarian_expression9)
rho10=calculate_spearman_corr(ovarian_expression10)


In [5]:
print(rho1)

[[1.         0.24869383 0.4018005  ... 0.26806929 0.36938349 0.24325215]
 [0.24869383 1.         0.60627361 ... 0.51315007 0.3054015  0.52217265]
 [0.4018005  0.60627361 1.         ... 0.61089543 0.31285668 0.48716341]
 ...
 [0.26806929 0.51315007 0.61089543 ... 1.         0.24100957 0.36581063]
 [0.36938349 0.3054015  0.31285668 ... 0.24100957 1.         0.28673338]
 [0.24325215 0.52217265 0.48716341 ... 0.36581063 0.28673338 1.        ]]


In [65]:
# Find overlapping gene between KEGG and the ovarian data
overlap_genes=list(set(ova_genes).intersection(set(Kegg_gene)))


In [67]:
print(len(overlap_genes))

2709


In [4]:
# Rebuild the KEGG network
import networkx as nx
G=nx.Graph()
for i in range(0,len(edgelist)):
    index1=edgelist.iloc[i,0]
    index2=edgelist.iloc[i,1]
    G.add_edge(nodes.iloc[index1,0],nodes.iloc[index2,0])
print(len(list(G.nodes())))
print(nx.diameter(G))

4867
34


In [75]:
print(list(G.nodes())[0])

hsa:226


In [91]:
import numpy as np
# Calculate the distance matrix (geodesic distance between each of the two nodes)
# In the distance matrix, row=source, column=target
length=dict(nx.all_pairs_shortest_path_length(G))
distance=np.ones((len(list(G.nodes())),len(list(G.nodes()))))
for i in range(0,len(list(G.nodes()))):
    for j in range(i,len(list(G.nodes()))):
        distance[i,j]=length[list(G.nodes())[i]][list(G.nodes())[j]]
        distance[j,i]=length[list(G.nodes())[j]][list(G.nodes())[i]]

In [94]:
print(np.amax(distance))

34.0


In [22]:
#build the SI component
#the SI component determines if a gene is more strongly correlated with its neighbors
def SI(distance_matrix,cor_matrix,diameter,genes_assayed_network,gene_of_interest):
    for i in range(0,diameter):
        for j in range(1,i+1):
            gene_of_interest
        
    

42873
42873
